name: Build Windows

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Before signing
      run: |
          echo "Looking at ${{ github.repository }} before signing"
          tree /F

    - name: Sign
      uses: azure/trusted-signing-action@v0.4.0
      with:
        azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
        azure-client-id: ${{ vars.AZURE_CLIENT_ID }}
        azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        endpoint: ${{ vars.AZURE_ENDPOINT }}
        trusted-signing-account-name: ${{ vars.AZURE_CODE_SIGNING_NAME }}
        certificate-profile-name: ${{ vars.AZURE_CERT_PROFILE_NAME }}
        files-folder: ${{ github.workspace }}
        files-folder-filter: exe,dll
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256

    - name: After signing
      run: |
          echo "Looking at ${{ github.repository }} (${{ github.ref }})after signing"
          tree /F
    
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        path: hello-go-cli.exe
        retention-days: 1
